serenity.test.root=com.automation.hu05
serenity.report.title=HU-05 Event Registration Automation Framework - Page Object Model
serenity.requirements.dir=src/test/resources/features
webdriver.driver=chrome
webdriver.autodownload.enabled=true
serenity.take.screenshots=FOR_EACH_ACTION
serenity.logging=INFO
serenity.verbose=true
headless.mode=false
